In [1]:
import numpy as np

### 基础知识

In [3]:
a = np.arange(15).reshape(3,5)

In [4]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [5]:
a.shape

(3, 5)

In [6]:
a.ndim

2

In [7]:
len(a.shape)

2

In [8]:
a.size

15

In [9]:
a.dtype

dtype('int64')

In [10]:
a.dtype.name

'int64'

In [11]:
a.itemsize

8

In [12]:
a.data

In [13]:
type(a)

numpy.ndarray

### 数组创建

In [14]:
a = np.array([2,3,4])

In [15]:
a

array([2, 3, 4])

In [20]:
type(a)

numpy.ndarray

In [21]:
a.dtype

dtype('int64')

In [17]:
b = np.array([1.5,2.5,3.5])

In [18]:
b

array([1.5, 2.5, 3.5])

In [19]:
type(b)

numpy.ndarray

In [22]:
b.dtype

dtype('float64')

In [26]:
c = np.array([((1,2),(3,4)), (4,5)])

In [27]:
c


array([[(1, 2), (3, 4)],
       [4, 5]], dtype=object)

In [28]:
c.ndim

2

In [29]:
d = np.array([(1,2),(3,4)], dtype = complex)

In [30]:
d

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [39]:
e = np.zeros((3,4));

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [37]:
np.ones((4,5), dtype = np.int32)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int32)

In [40]:
e.dtype

dtype('float64')

In [41]:
np.empty((2,3))

array([[-2.31584178e+077,  2.00390260e+000,  1.48219694e-323],
       [ 0.00000000e+000,  0.00000000e+000,  4.17201348e-309]])

In [42]:
np.arange(10,20,1)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [44]:
np.linspace(0,0.2,5)

array([0.  , 0.05, 0.1 , 0.15, 0.2 ])

打印数组


In [45]:
a = np.arange(6)

In [46]:
print(a)

[0 1 2 3 4 5]


In [47]:
b = np.arange(12).reshape(3,4)

In [48]:
print(b)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [56]:
c = np.arange(48).reshape(2,3,2,4)

In [57]:
print(c)

[[[[ 0  1  2  3]
   [ 4  5  6  7]]

  [[ 8  9 10 11]
   [12 13 14 15]]

  [[16 17 18 19]
   [20 21 22 23]]]


 [[[24 25 26 27]
   [28 29 30 31]]

  [[32 33 34 35]
   [36 37 38 39]]

  [[40 41 42 43]
   [44 45 46 47]]]]


### 基本操作

In [59]:
a = np.array([20,30,40,50])

In [61]:
b = np.arange(4)

In [62]:
b


array([0, 1, 2, 3])

In [63]:
c = a-b

In [64]:
c

array([20, 29, 38, 47])

In [65]:
b**2


array([0, 1, 4, 9])

In [67]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [68]:
a<35

array([ True,  True, False, False])

In [69]:
A = np.array([[1,1],[0,1]])
B = np.array([[2,0],[3,4]])

In [70]:
A*B

array([[2, 0],
       [0, 4]])

In [71]:
A@B

array([[5, 4],
       [3, 4]])

In [72]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [73]:
a = np.ones((2,3), dtype = int)

In [74]:
b = np.random.random((2,3))

In [75]:
a

array([[1, 1, 1],
       [1, 1, 1]])

In [76]:
a *= 3

In [77]:
a

array([[3, 3, 3],
       [3, 3, 3]])

In [78]:
b

array([[0.17148824, 0.47199207, 0.51465187],
       [0.07153699, 0.71955033, 0.02873168]])

In [79]:
b += a 

In [80]:
b

array([[3.17148824, 3.47199207, 3.51465187],
       [3.07153699, 3.71955033, 3.02873168]])

In [81]:
a += b

UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

In [82]:
a = np.ones(3, dtype = np.int32)

In [84]:
b = np.linspace(0,np.pi,3)

In [85]:
b.dtype.name

'float64'

In [86]:
c = a + b;c;c.dtype.name

'float64'

In [88]:
a = np.arange(12).reshape((3,4))

In [95]:
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [91]:
a.sum(axis = 0)

array([12, 15, 18, 21])

In [92]:
a.sum(axis = 1)

array([ 6, 22, 38])

In [94]:
a.min(axis = 0)

array([0, 1, 2, 3])

### 索引，切片和迭代

In [96]:
a = np.arange(10)**3

In [97]:
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [98]:
a[2]

8

In [99]:
a[2:5]

array([ 8, 27, 64])

In [100]:
a[:6:2] = -1000

In [101]:
a

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,
         729])

In [102]:
a[::-1]

array([  729,   512,   343,   216,   125, -1000,    27, -1000,     1,
       -1000])

In [108]:
for i in a:
    print(i**(1/3.))
    

nan
1.0
nan
3.0
nan
4.999999999999999
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


/Users/kevin/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in power
  


In [109]:
def f(x,y):
    return 10*x + y


In [110]:
a = np.fromfunction(f,(4,5), dtype = int)

In [111]:
a

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

In [112]:
a[:4, 1]

array([ 1, 11, 21, 31])

In [113]:
a[1,:4]

array([10, 11, 12, 13])

In [114]:
a[2,3]

23

In [115]:
a[-1]

array([30, 31, 32, 33, 34])

In [116]:
c = np.array( [[[  0,  1,  2],               # a 3D array (two stacked 2D arrays)
...                 [ 10, 12, 13]],
...                [[100,101,102],
...                 [110,112,113]]])

In [117]:
c

array([[[  0,   1,   2],
        [ 10,  12,  13]],

       [[100, 101, 102],
        [110, 112, 113]]])

In [118]:
c[1,...]

array([[100, 101, 102],
       [110, 112, 113]])

In [119]:
c[...,-1]

array([[  2,  13],
       [102, 113]])

In [121]:
for row in a:
    print(row)

[0 1 2 3 4]
[10 11 12 13 14]
[20 21 22 23 24]
[30 31 32 33 34]


In [122]:
for element in a.flat:
    print(element)

0
1
2
3
4
10
11
12
13
14
20
21
22
23
24
30
31
32
33
34
